# Generated by Django 5.1.7 on 2026-02-13 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_dataset_is_current_dataset_schema_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chart_type', models.CharField(max_length=50)),
                ('x_axis', models.CharField(max_length=100)),
                ('y_axis', models.CharField(max_length=100)),
                ('aggregation', models.CharField(default='sum', max_length=20)),
                ('limit', models.CharField(default='10', max_length=10)),
                ('filter_op', models.CharField(blank=True, max_length=10, null=True)),
                ('filter_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
